### ISSUE TITLE
poeprices.info prediction missing league

### ISSUE THREAD

**Issue by LeviMcCracken** [r52/pta-next#10]
**Describe the bug**
CtrlD shows a toast "Error querying poeprices.info"
There is a green square int the top left that used to show the league selected to search

**To Reproduce**

**Expected behavior**
A tab to come up with a poeprices.info prediction

**Screenshots**

**Additional context**
![image](https://user-images.githubusercontent.com/35898208/80914104-bc7f4900-8d06-11ea-8d2b-362334b74def.png)
![image](https://user-images.githubusercontent.com/35898208/80914134-dcaf0800-8d06-11ea-82b0-9e9d823eb2e3.png)

**Comment by r52** [comment]
When it's missing the league tag like that, that means the league data failed to download in the first place. When you see something like this, the first thing to try is to restart the app. I'll think about placing popup errors when essential data cannot be downloaded so that it doesn't lead others into thinking the app is working properly.

**Comment by r52** [comment]
[v0.1.1](https://github.com/r52/pta-next/releases/tag/v0.1.1) now errors when essential data failed to download.
