### ISSUE TITLE
PoE - Cheat Sheets

### ISSUE THREAD

**Issue by gixxpunk** [r52/pta-next#20]
Thanks for your awesome tool!

Would be nice if you could implement the usual cheat sheets (especially Incursion (F5), Betrayal (F6)) into your tool.

Keep up your good work!
![Betrayal](https://user-images.githubusercontent.com/1607735/86510258-7cb00d00-bdee-11ea-9d49-44ea88c3f5d8.png)
![Incursion](https://user-images.githubusercontent.com/1607735/86510259-7faafd80-bdee-11ea-84db-b2efaa6faaa6.png)

**Comment by r52** [comment]
I've been thinking about this one for a while since MercuryTrade also had it. However, there are so many of these being spread around made by different people with different standards on their grading of specific masters/rooms. On top of that, sometimes new things get added for specific masters and whatnot and I'm never sure whether these are still relevant. For example, I'm still using [this one](https://i.imgur.com/KpSJB1j.png) which I've been using since 3.9. It would be nice to see and compare a couple of these before deciding on one to use.

**Comment by gixxpunk** [comment]
I also like your version of the betrayal sheet. Maybe add selected defaults into a config folder where users than can simply overwrite the pictures with their own ones if they do not like the default version?
