### ISSUE TITLE
Test notification not visible

### ISSUE THREAD

**Issue by gixxpunk** [r52/pta-next#22]
Test notifications from Trade UI do not show up properly most of the time. This happens on a dual monitor setup with and without Vulcan render enabled in game.

The only way to get the notification(s) shown up properly after pressing the button several times is to open and close pta-next settings menu.

**Comment by r52** [comment]
I can't reproduce this on DX11 Fullscreen Windowed nor Vulkan emulated Fullscreen Windowed. I'm assuming the trade bar works for you since you are using it for the test notifications, but as far as the source code goes, the trade bar and the trade notification has the same Z priority since their foreground hooks get executed at the same time. The only issue I've encountered (and tried to fix in the recent 0.1.9) is when neither show up. See [this issue](https://github.com/r52/PTA/issues/37) for a possibly related issue/solution.

**Comment by r52** [comment]
Give the new dev build a try to see if it helps.

**Comment by gixxpunk** [comment]
Thanks, seems to work well now with PTA-Next v0.1.9. Tried several times (vulcan render with your fullscreen fix eneabled) to reproduce the bug and the problem seems fixed.
