### ISSUE TITLE
Reduced mods

### ISSUE THREAD

**Issue by Wobein** [r52/pta-next#6]
Many mods associated with reduction are defined as increase.

**Cheap Construction**: **reduced** Trap Duration
**Rain of Splinters**: **reduced** Totem Damage
**Uul-Netol's Kiss** and **Uul-Netol's Embrace**: **reduced** Attack Speed
**Curtain Call**: **reduced** Mine Throwing Speed
**Rare item**: **reduced** Mana Reserved

All the things from the description I have and can provide for parsing.

**Comment by r52** [comment]
This is not a bug and is correct. All of these mods with a "reduced" parameter is actually defined internally in PoE as an "increased" parameter with a negative value. Since PTA passes these parameters directly to the search site (i.e. as "increased" with a negative value) I do not want to add a level of obfuscation by changing these for user experience. These kind of things have the potential to become a maintenance nightmare if GGG decides to change how they word some of these mods in the future.
