### ISSUE TITLE
Requests

### ISSUE THREAD

**Issue by Wobein** [r52/pta-next#9]
Wishlist for convenience:
- remove from the list of mods that do not have rolls (or customizable through settings)
saves screen space, thereby speeding up pricing
- create a discord server (I did not find the links)
will allow you to interact more quickly with people and feedback
- create a forum topic
will allow you to collect a database of testers to transfer them to discord and take away from the author all the remaining time from real life
- make grouping of links, ilvl and base more clearly and conveniently (in my opinion), yellow in one line and blue in another, there will be more space for corrupt box
![image](https://i.imgur.com/3qVIekx.png)
- add icons instead of names for currency? interesting to see
In any case, i used all the programs for checking prices, and yours is the most convenient and fastest, even at this stage it is not inferior to most others. Do not give up development please.
_Sorry for my spelling mistakes._

**Comment by r52** [comment]
First of all, thanks for the suggestions!

> * remove from the list of mods that do not have rolls (or customizable through settings)
>  saves screen space, thereby speeding up pricing

Note that this would also remove the notable mods from cluster jewels. Not sure if I want this.

> * create a discord server (I did not find the links)
>   will allow you to interact more quickly with people and feedback
> * create a forum topic
>   will allow you to collect a database of testers to transfer them to discord and take away from the author all the remaining time from real life

Sorry, but as convenient as it sounds from a feedback point of view, I personally don't have the time nor patience to manage a community full of spam and differing opinions. I would much rather have all of that stay here at GitHub Issues so that it encourages people to create an account and file neat and descriptive reports/suggestions if they _really_ want to suggest improvements to the app (such as yourself), rather than having to wade through a chatroom or forum thread full of what will probably be undescriptive reports and suggestions.

> * make grouping of links, ilvl and base more clearly and conveniently (in my opinion), yellow in one line and blue in another, there will be more space for corrupt box
> * add icons instead of names for currency? interesting to see

Good points, I'll look into this.

**Comment by Wobein** [comment]
Well, how do you plan to accumulate a user base that you publish on Reddit?
In any case, you can not support the topic on the forum and explain your position. I can’t come up with options to attract more people and compete well with others.

**Comment by r52** [comment]
Well the thing is I never intended to publicize this app at all. This app (as well as the old PTA) was mainly made for myself and a few other close friends who wanted this specific set of features which no other tool had on its own when I first started the project. Those that found out about this app stumbled upon it by themselves, and those who decided to publicize on it Reddit or elsewhere did so of their own free will. While I certainly welcome some word of mouth promotion and well thought out feedback, I simply don't have the time to actively engage the community or promote the app (because like I said, that isn't the intention). After all, I'm just one guy with very limited free time.

**Comment by Wobein** [comment]
> Separate socket/link and ilvl/base toggles in mod page

Amazing, it has become more understandable and clear to work with searches for only bases of things with influences. This may seem like nit-picking or my incorrect question before, but how about saving an extra line of the interface? Minimalism and experience with the macro trade require me to report this. :D
![image](https://i.imgur.com/fMk2smA.jpg)

> Add currency images to price results 

Thank you, it looks very beautiful.

> who decided to publicize on it Reddit

I do not have an account on reddit and for one post to create it does not sound very good to me. But I hope that those who read it will take similar steps and correctly present it.
Maybe it's time to make a release? The program is very stable and there are no critical bugs. I would boldly give the program a 0.8-1.0 version. Perhaps you still have ideas for implementation in the plans?

**Comment by r52** [comment]
> ![image](https://camo.githubusercontent.com/00bdecafb781564ffac381868c02047b0fb33893/68747470733a2f2f692e696d6775722e636f6d2f664d6b32736d412e6a7067)

 Done

> Maybe it's time to make a release? The program is very stable and there are no critical bugs. I would boldly give the program a 0.8-1.0 version. Perhaps you still have ideas for implementation in the plans?

I'll probably put out a release after finishing #8.

**Comment by r52** [comment]
Closing as completed.
